import numpy as np

NYU_V2_segmentation_classes = [
    "otherprop",
    "wall",
    "floor",
    "cabinet",
    "bed",
    "chair",
    "sofa",
    "table",
    "door",
    "window",
    "bookshelf",
    "picture",
    "counter",
    "blinds",
    "desk",
    "shelves",
    "curtain",
    "dresser",
    "pillow",
    "mirror",
    "floor mat",
    "clothes",
    "ceiling",
    "books",
    "refrigerator",
    "television",
    "paper",
    "towel",
    "shower curtain",
    "box",
    "whiteboard",
    "person",
    "night stand",
    "toilet",
    "sink",
    "lamp",
    "bathtub",
    "bag",
    "otherstructure",
    "otherfurniture",
]
NYU_V2_segmentation_13classes = [
    "window",
    "bed",
    "books",
    "ceiling",
    "chair",
    "floor",
    "furniture",
    "objects",
    "picture",
    "sofa",
    "table",
    "tv",
    "wall",
]

SCENE_IDS = {
    "bedroom": 0,
    "home_office": 1,
    "playroom": 2,
    "indoor_balcony": 3,
    "office": 4,
    "living_room": 5,
    "kitchen": 6,
    "furniture_store": 7,
    "office_kitchen": 8,
    "home_storage": 9,
    "laundry_room": 10,
    "excercise_room": 11,
    "student_lounge": 12,
    "printer_room": 13,
    "classroom": 14,
    "reception_room": 15,
    "bookstore": 16,
    "dining_room": 17,
    "bathroom": 18,
    "study_room": 19,
    "conference_room": 20,
    "study": 21,
    "basement": 22,
    "cafe": 23,
    "computer_lab": 24,
    "dinette": 25,
    "foyer": 26,
}


SCENE_MERGED = {
    "bathroom": "bathroom",
    "bedroom": "bedroom",
    "living_room": "living_room",
    "dining_room": "dining_room",
    "dinette": "dining_room",
    "kitchen": "kitchen",
    "office": "office",
    "office_kitchen": "office",
    "conference_room": "office",
    "reception_room": "office",
    "printer_room": "office",
    "home_office": "office",
    "playroom": "other_indoor",
    "indoor_balcony": "other_indoor",
    "furniture_store": "other_indoor",
    "home_storage": "other_indoor",
    "laundry_room": "other_indoor",
    "excercise_room": "other_indoor",
    "student_lounge": "other_indoor",
    "classroom": "other_indoor",
    "bookstore": "other_indoor",
    "study_room": "other_indoor",
    "study": "other_indoor",
    "basement": "other_indoor",
    "cafe": "other_indoor",
    "computer_lab": "other_indoor",
    "foyer": "other_indoor",
}

SCENE_MERGED_IDS = {val: idx for idx, val in enumerate(set(SCENE_MERGED.values()))}
MERGED_SCENES_IDS = {idx: val for idx, val in enumerate(set(SCENE_MERGED.values()))}
