NYU_V2_classes = [
    "otherprop",
    "wall",
    "floor",
    "cabinet",
    "bed",
    "chair",
    "sofa",
    "table",
    "door",
    "window",
    "bookshelf",
    "picture",
    "counter",
    "blinds",
    "desk",
    "shelves",
    "curtain",
    "dresser",
    "pillow",
    "mirror",
    "floor mat",
    "clothes",
    "ceiling",
    "books",
    "refrigerator",
    "television",
    "paper",
    "towel",
    "shower curtain",
    "box",
    "whiteboard",
    "person",
    "night stand",
    "toilet",
    "sink",
    "lamp",
    "bathtub",
    "bag",
    "otherstructure",
    "otherfurniture",
]

SCENE_IDS = {
    "bedroom": 0,
    "home_office": 1,
    "playroom": 2,
    "indoor_balcony": 3,
    "office": 4,
    "living_room": 5,
    "kitchen": 6,
    "furniture_store": 7,
    "office_kitchen": 8,
    "home_storage": 9,
    "laundry_room": 10,
    "excercise_room": 11,
    "student_lounge": 12,
    "printer_room": 13,
    "classroom": 14,
    "reception_room": 15,
    "bookstore": 16,
    "dining_room": 17,
    "bathroom": 18,
    "study_room": 19,
    "conference_room": 20,
    "study": 21,
    "basement": 22,
    "cafe": 23,
    "computer_lab": 24,
    "dinette": 25,
    "foyer": 26,
}
